name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare
        env:
          GO111MODULE: on
        run: |
          echo "install dependency"
          sudo apt-get update
          sudo apt-get install -y gnupg2 systemd-container
          echo "install ghr"
          curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz > ghr.tar.gz
          tar xvzf ghr.tar.gz
          sudo mv ./ghr_v0.13.0_linux_amd64/ghr /usr/local/sbin
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "build images"
          cd $GITHUB_WORKSPACE
          dt=$(date -d '30 days ago' +"%Y-%m-%d")
          for GROUP in stable beta alpha
          do
            for VERSION in $(curl -s https://coreos.com/releases/releases-$GROUP.json | jq --arg dt $dt --raw-output 'to_entries[] | select(.value.release_date > $dt) | .key')
            do
              echo "build image for $GROUP-$VERSION"
              chmod +x ./ci.sh
              ./ci.sh $GROUP $VERSION
            done
          done

